# Generated by Django 4.0.2 on 2022-04-19 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.DateField(blank=True, default=datetime.date(1, 1, 1)),
        ),
    ]
